//---------------------------------------------------------------------------

#ifndef MainFormUnitH
#define MainFormUnitH
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <FMX.Controls.hpp>
#include <FMX.Forms.hpp>
#include <FMX.Objects.hpp>
#include <FMX.Types.hpp>
#include <FMX.Layouts.hpp>
#include <FMX.StdCtrls.hpp>
#include <FMX.Menus.hpp>
#include <FMX.ActnList.hpp>
#include <System.Actions.hpp>
#include <FMX.Controls.Presentation.hpp>
#include <FMX.Effects.hpp>
#include <FMX.Ani.hpp>
#include <System.IniFiles.hpp>
#include <FMX.Media.hpp>
#include <map>
#include <cstdlib>
#include <ctime>
using namespace std;
class Pair{
	public:
	int first;
	int second;
};
//---------------------------------------------------------------------------
class TMainForm : public TForm
{
__published:	// IDE-managed Components
	TLayout *GameWindow;
	TRectangle *GameBackGround;
	TPath *FreeSpace1_2;
	TPath *FreeSpace1_3;
	TPath *FreeSpace1_4;
	TPath *FreeSpace1_1;
	TPath *FreeSpace1_5;
	TPath *FreeSpace1_13;
	TPath *FreeSpace2_1;
	TPath *FreeSpace2_2;
	TPath *FreeSpace2_3;
	TPath *FreeSpace2_4;
	TPath *FreeSpace2_5;
	TPath *FreeSpace2_13;
	TPath *FreeSpace3_1;
	TPath *FreeSpace3_2;
	TPath *FreeSpace3_3;
	TPath *FreeSpace3_4;
	TPath *FreeSpace3_5;
	TPath *FreeSpace3_13;
	TPath *FreeSpace4_1;
	TPath *FreeSpace4_2;
	TPath *FreeSpace4_3;
	TPath *FreeSpace4_4;
	TPath *FreeSpace4_5;
	TPath *FreeSpace4_13;
	TPath *FreeSpace5_2;
	TPath *FreeSpace5_3;
	TPath *FreeSpace5_4;
	TPath *FreeSpace5_5;
	TPath *FreeSpace5_13;
	TPath *FreeSpace9_1;
	TPath *FreeSpace9_2;
	TPath *FreeSpace9_3;
	TPath *FreeSpace9_4;
	TPath *FreeSpace9_5;
	TPath *FreeSpace9_13;
	TPath *FreeSpace6_1;
	TPath *FreeSpace7_1;
	TPath *FreeSpace9_6;
	TPath *FreeSpace9_7;
	TPath *FreeSpace6_2;
	TPath *FreeSpace6_3;
	TPath *FreeSpace7_2;
	TPath *FreeSpace7_3;
	TPath *FreeSpace6_4;
	TPath *FreeSpace7_4;
	TPath *FreeSpace6_5;
	TPath *FreeSpace7_5;
	TPath *FreeSpace1_6;
	TPath *FreeSpace1_7;
	TPath *FreeSpace1_8;
	TPath *FreeSpace1_9;
	TPath *FreeSpace8_1;
	TPath *FreeSpace8_2;
	TPath *FreeSpace8_3;
	TPath *FreeSpace8_4;
	TPath *FreeSpace8_5;
	TPath *FreeSpace5_1;
	TLayout *FirstWindow;
	TRectangle *Background_Image;
	TRectangle *PlayButton;
	TLabel *Label1;
	TShadowEffect *ShadowEffect;
	TColorAnimation *ColorAnimation2;
	TPath *FreeSpace2_6;
	TPath *FreeSpace3_6;
	TPath *FreeSpace4_6;
	TPath *FreeSpace5_6;
	TPath *FreeSpace6_6;
	TPath *FreeSpace7_6;
	TPath *FreeSpace8_6;
	TPath *FreeSpace2_7;
	TPath *FreeSpace3_7;
	TPath *FreeSpace4_7;
	TPath *FreeSpace5_7;
	TPath *FreeSpace6_7;
	TPath *FreeSpace7_7;
	TPath *FreeSpace8_7;
	TPath *FreeSpace9_8;
	TPath *FreeSpace8_8;
	TPath *FreeSpace7_8;
	TPath *FreeSpace6_8;
	TPath *FreeSpace5_8;
	TPath *FreeSpace4_8;
	TPath *FreeSpace3_8;
	TPath *FreeSpace2_8;
	TPath *FreeSpace9_9;
	TPath *FreeSpace9_10;
	TPath *FreeSpace2_9;
	TRectangle *SettingsButton;
	TLabel *Label2;
	TShadowEffect *ShadowEffect1;
	TColorAnimation *ColorAnimation1;
	TRectangle *CloseButton;
	TLabel *Label3;
	TShadowEffect *ShadowEffect2;
	TColorAnimation *ColorAnimation3;
	TLayout *Space;
	TPath *FreeSpace3_9;
	TPath *FreeSpace9_11;
	TPath *FreeSpace9_12;
	TPath *FreeSpace1_10;
	TPath *FreeSpace1_11;
	TPath *FreeSpace1_12;
	TPath *FreeSpace6_13;
	TPath *FreeSpace7_13;
	TPath *FreeSpace8_13;
	TPath *FreeSpace2_10;
	TPath *FreeSpace3_10;
	TPath *FreeSpace4_9;
	TPath *FreeSpace4_10;
	TPath *FreeSpace2_11;
	TPath *FreeSpace3_11;
	TPath *FreeSpace5_9;
	TPath *FreeSpace6_9;
	TPath *FreeSpace5_10;
	TPath *FreeSpace6_10;
	TPath *FreeSpace8_9;
	TPath *FreeSpace7_9;
	TPath *FreeSpace2_12;
	TPath *FreeSpace3_12;
	TPath *FreeSpace4_11;
	TPath *FreeSpace4_12;
	TPath *FreeSpace5_11;
	TPath *FreeSpace5_12;
	TPath *FreeSpace6_11;
	TPath *FreeSpace7_10;
	TPath *FreeSpace6_12;
	TPath *FreeSpace8_10;
	TPath *FreeSpace7_11;
	TPath *FreeSpace7_12;
	TPath *FreeSpace8_12;
	TPath *FreeSpace8_11;
	TRectangle *Rectangle2;
	TRectangle *ExamplePictureOut;
	TInnerGlowEffect *InnerGlowEffect1;
	TRectangle *ExamplePicture;
	TLayout *LevelsWindow;
	TRectangle *LevelBackground;
	TRectangle *Copy;
	TRectangle *Rectangle1;
	TShadowEffect *ShadowEffect4;
	TPath *Path1_1;
	TPath *Path1_10;
	TPath *Path1_11;
	TPath *Path1_12;
	TPath *Path1_13;
	TPath *Path1_2;
	TPath *Path1_3;
	TPath *Path1_4;
	TPath *Path1_5;
	TPath *Path1_6;
	TPath *Path1_7;
	TPath *Path1_8;
	TPath *Path1_9;
	TPath *Path2_1;
	TPath *Path2_10;
	TPath *Path2_11;
	TPath *Path2_12;
	TPath *Path2_13;
	TPath *Path2_2;
	TPath *Path2_3;
	TPath *Path2_4;
	TPath *Path2_5;
	TPath *Path2_6;
	TPath *Path2_7;
	TPath *Path2_8;
	TPath *Path2_9;
	TPath *Path3_1;
	TPath *Path3_10;
	TPath *Path3_11;
	TPath *Path3_12;
	TPath *Path3_13;
	TPath *Path3_2;
	TPath *Path3_3;
	TPath *Path3_4;
	TPath *Path3_5;
	TPath *Path3_6;
	TPath *Path3_7;
	TPath *Path3_8;
	TPath *Path3_9;
	TPath *Path4_1;
	TPath *Path4_10;
	TPath *Path4_11;
	TPath *Path4_12;
	TPath *Path4_13;
	TPath *Path4_2;
	TPath *Path4_3;
	TPath *Path4_4;
	TPath *Path4_5;
	TPath *Path4_6;
	TPath *Path4_7;
	TPath *Path4_8;
	TPath *Path4_9;
	TPath *Path5_1;
	TPath *Path5_10;
	TPath *Path5_11;
	TPath *Path5_12;
	TPath *Path5_13;
	TPath *Path5_2;
	TPath *Path5_3;
	TPath *Path5_4;
	TPath *Path5_5;
	TPath *Path5_6;
	TPath *Path5_7;
	TPath *Path5_8;
	TPath *Path5_9;
	TPath *Path6_1;
	TPath *Path6_10;
	TPath *Path6_11;
	TPath *Path6_12;
	TPath *Path6_13;
	TPath *Path6_2;
	TPath *Path6_3;
	TPath *Path6_4;
	TPath *Path6_5;
	TPath *Path6_6;
	TPath *Path6_7;
	TPath *Path6_8;
	TPath *Path6_9;
	TPath *Path7_1;
	TPath *Path7_10;
	TPath *Path7_11;
	TPath *Path7_12;
	TPath *Path7_13;
	TPath *Path7_2;
	TPath *Path7_3;
	TPath *Path7_4;
	TPath *Path7_5;
	TPath *Path7_6;
	TPath *Path7_7;
	TPath *Path7_8;
	TPath *Path7_9;
	TPath *Path8_1;
	TPath *Path8_10;
	TPath *Path8_11;
	TPath *Path8_12;
	TPath *Path8_13;
	TPath *Path8_2;
	TPath *Path8_3;
	TPath *Path8_4;
	TPath *Path8_5;
	TPath *Path8_6;
	TPath *Path8_7;
	TPath *Path8_8;
	TPath *Path8_9;
	TPath *Path9_1;
	TPath *Path9_10;
	TPath *Path9_11;
	TPath *Path9_12;
	TPath *Path9_13;
	TPath *Path9_2;
	TPath *Path9_3;
	TPath *Path9_4;
	TPath *Path9_5;
	TPath *Path9_6;
	TPath *Path9_7;
	TPath *Path9_8;
	TPath *Path9_9;
	TMediaPlayer *MediaPlayer1;
	TLayout *SettingsLayout;
	TRectangle *SettingsBg;
	TRectangle *SettingsIcon;
	TRectangle *BlackBg;
	TImage *Image1;
	TInnerGlowEffect *InnerGlowEffect2;
	TShadowEffect *ShadowEffect5;
	TCheckBox *MusicCheckBox;
	TLabel *MusicLabel;
	TLayout *MusicLayout;
	TRectangle *Rectangle5;
	TInnerGlowEffect *InnerGlowEffect3;
	TLayout *SoundEffectLayout;
	TRectangle *Rectangle6;
	TCheckBox *SoundEffectCheckBox;
	TLabel *Label4;
	TInnerGlowEffect *InnerGlowEffect4;
	TLayout *ClearHistoryLayout;
	TRectangle *Rectangle4;
	TLabel *Label5;
	TShadowEffect *ShadowEffect7;
	TLayout *SaveSettings;
	TRectangle *Rectangle7;
	TLabel *Label6;
	TShadowEffect *ShadowEffect8;
	TLayout *CancelSettings;
	TRectangle *Rectangle8;
	TLabel *Label7;
	TShadowEffect *ShadowEffect9;
	TRectangle *WarningBlackBg;
	TLayout *WarningLayout;
	TRectangle *WarningBg;
	TLabel *WarningText;
	TLayout *WarningNoBtn;
	TRectangle *Rectangle3;
	TLabel *Label8;
	TShadowEffect *ShadowEffect6;
	TLayout *WarningYesBtn;
	TRectangle *Rectangle9;
	TLabel *Label9;
	TShadowEffect *ShadowEffect10;
	TColorAnimation *ColorAnimation4;
	TColorAnimation *ColorAnimation5;
	TFloatAnimation *FloatAnimation1;
	TFloatAnimation *FloatAnimation2;
	TFloatAnimation *FloatAnimation3;
	TFloatAnimation *FloatAnimation4;
	TFloatAnimation *FloatAnimation5;
	TLayout *GameWarningLayout;
	TRectangle *Rectangle10;
	TLabel *GameWarningLabel;
	TLayout *GameWarningNoBtn;
	TRectangle *Rectangle11;
	TLabel *Label11;
	TShadowEffect *ShadowEffect11;
	TFloatAnimation *FloatAnimation6;
	TLayout *GameWarningYesBtn;
	TRectangle *Rectangle12;
	TLabel *Label12;
	TShadowEffect *ShadowEffect12;
	TFloatAnimation *FloatAnimation7;
	TShadowEffect *ShadowEffect13;
	TRectangle *GameBlackBg;
	TRectangle *Rectangle13;
	TShadowEffect *ShadowEffect14;
	TLayout *NextLevelLayout;
	TRectangle *NextLevelBg;
	TLabel *NextLevelLabel;
	TRectangle *Rectangle14;
	TLayout *GoButton;
	TLabel *Label10;
	TRectangle *StarPicture;
	TShadowEffect *ShadowEffect3;
	TTimer *Timer1;
	TLayout *TimerLayout;
	TRectangle *Rectangle16;
	TLabel *HourLabel;
	TLabel *label;
	TLabel *MinutLabel;
	TLabel *Label13;
	TLabel *SekundLabel;
	TFloatAnimation *ExamplePictureWidthAnimation;
	TFloatAnimation *ExamplePictureHeightAnimation;
	TFloatAnimation *ExamplePicturePositionXAnimation;
	TFloatAnimation *ExamplePicturePositionYAnimation;
	void __fastcall CloseButtonClick(TObject *Sender);
	void __fastcall PlayButtonMouseEnter(TObject *Sender);
	void __fastcall PlayButtonMouseLeave(TObject *Sender);
	void __fastcall FreeSpace1_1MouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          float X, float Y);
	void __fastcall FreeSpace1_1MouseMove(TObject *Sender, TShiftState Shift, float X,
          float Y);
	void __fastcall FreeSpace1_1MouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          float X, float Y);
	void __fastcall PlayButtonClick(TObject *Sender);
	//void __fastcall LevelButtonClick(TObject *Sender);
	void __fastcall LevelButtonOnMouseEnter(TObject *Sender);
	void __fastcall LevelButtonOnMouseLeave(TObject *Sender);
	void __fastcall Rectangle1Click(TObject *Sender);
	void __fastcall LevelsWindowCreate();
	void __fastcall Accomodation(TObject *Sender);
	//void __fastcall Check();
	void __fastcall PlayGame(int level);
	void __fastcall SettingsButtonClick(TObject *Sender);
	void __fastcall SettingsExitClick(TObject *Sender);
	void __fastcall SettingsCheck();
	void __fastcall SaveSettingsClick(TObject *Sender);
	void __fastcall PlayMusic(int Music);
	void __fastcall ClearHistoryLayoutClick(TObject *Sender);
	void __fastcall WarningNoBtnClick(TObject *Sender);
	void __fastcall WarningYesBtnClick(TObject *Sender);
	void __fastcall ClearHistoryLayoutMouseEnter(TObject *Sender);
	void __fastcall ClearHistoryLayoutMouseLeave(TObject *Sender);
	void __fastcall Rectangle13Click(TObject *Sender);
	void __fastcall GameWarningNoBtnClick(TObject *Sender);
	void __fastcall GameWarningYesBtnClick(TObject *Sender);
	void __fastcall Winner();
	void __fastcall Timer1Timer(TObject *Sender);
    void __fastcall LevelsClick(TObject *Sender);
	void __fastcall GoButtonClick(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall FreeSpace1_1DblClick(TObject *Sender);
	void __fastcall FormActivate(TObject *Sender);
	void __fastcall ExamplePictureOutClick(TObject *Sender);
	void __fastcall ExamplePictureWidthAnimationFinish(TObject *Sender);
	void __fastcall ExamplePictureHeightAnimationFinish(TObject *Sender);
	void __fastcall FormResize(TObject *Sender);
   //	void __fastcall Check();
private:	// User declarations
public:		// User declarations
	__fastcall TMainForm(TComponent* Owner);

};
//---------------------------------------------------------------------------
extern PACKAGE TMainForm *MainForm;
bool isDown, isExamplePictureLarge;
int Win, LevelCount, pX = 40, pY = 100, StarsCount, isFull, DinComCount;
float H,W, PosX, PosY, hX, hY;
String sIndex_i, sIndex_j;
int index_i, index_j, Sound, Music, Current_Level;
TIniFile *File, *f, *sFile, *F;
String CURRENT_DIR;
TRectangle *R[15], *S[15], *Locked;
TRectangle *Lock;
TShadowEffect *Effect;
TPath *FreePath[10][14], *ImagePath[10][14];
std::map <String, Pair> isBusy;
int StartTimeHour,StartTimeMinut,StartTimeSekund, StopTimeHour,StopTimeMinut,StopTimeSekund, TimerHour, TimerMinut, TimerSekund;
int Hour, Minut, Sekund, tagation[10][15];
//---------------------------------------------------------------------------
#endif
